[main]
horizontal-pad=0
vertical-pad=0
line-height=32
width=64
prompt=" > "
[border]
radius=0
[colors]
# catppuccin mocha
background=11111bff
text=bac2deff
prompt=6c7086ff
placeholder=7f849cff
input=cdd6f4ff
match=89b4faff
selection=1e1e2eff
selection-text=cdd6f4ff
selection-match=fab387ff
counter=7f849cff
border=00000000
